CREATE TABLE IF NOT EXISTS `users` (
	`uuid` BINARY(16) PRIMARY KEY,
	`email` VARCHAR(191) NOT NULL,
	`username` VARCHAR(191) UNIQUE NOT NULL,
	`password` BINARY(64) NOT NULL,
	`email_on_comment` BOOL NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS `uploads` (
	`uuid` BINARY(16) PRIMARY KEY,
	`user` BINARY(16) NOT NULL,
	`like_count` INT NOT NULL DEFAULT 0,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`user`) REFERENCES `users`(`uuid`)
);

CREATE TABLE IF NOT EXISTS `comments` (
	`upload` BINARY(16) NOT NULL,
	`user` BINARY(16) NOT NULL,
	`text` TEXT NOT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (`user`) REFERENCES `users`(`uuid`) ON DELETE CASCADE,
	FOREIGN KEY (`upload`) REFERENCES `uploads`(`uuid`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `likes` (
	`upload` BINARY(16) NOT NULL,
	`user` BINARY(16) NOT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`user`) REFERENCES `users`(`uuid`) ON DELETE CASCADE,
	FOREIGN KEY (`upload`) REFERENCES `uploads`(`uuid`) ON DELETE CASCADE
);
